Cleanup
Removed 32bit/BIOS code, cleaned up build scripts a little.

diff --git a/images/buildUEFI64 b/images/buildUEFI64
--- a/images/buildUEFI64
+++ b/images/buildUEFI64
@@ -1,37 +1,53 @@
-#!/bin/bash
+#! /bin/bash
 set -x
-# Build a custom UEFI linux based PBA image
-## define releases for tools
 . conf
-VERSIONINFO=`git describe --dirty`  || VERSIONINFO=tarball
-BUILDTYPE=UEFI64
-BUILDIMG=${BUILDTYPE}-${VERSIONINFO}.img
 
-## check that everything is available
-[  -f scratch/${SYSLINUX}/efi64/efi/syslinux.efi ] || { echo " prereqs are not available "; exit 1; }
-[  -f scratch/${SYSLINUX}/efi64/com32/elflink/ldlinux/ldlinux.e64 ] || { echo " prereqs are not available "; exit 1; }
-[  -f scratch/buildroot/64bit/images/bzImage ] || { echo " prereqs are not available "; exit 1; }
-[  -f scratch/buildroot/64bit/images/rootfs.cpio.xz ] || { echo " prereqs are not available "; exit 1; }
-[  -f scratch/buildroot/64bit/target/sbin/linuxpba  ] || { echo " prereqs are not available "; exit 1; }
-[  -f scratch/buildroot/64bit/target/sbin/sedutil-cli  ] || { echo " prereqs are not available "; exit 1; }
-[  -f buildroot/syslinux.cfg ] || { echo " prereqs are not available "; exit 1; }
+# Build a custom UEFI linux based PBA image
+VERSIONINFO="$(git describe --dirty)" || VERSIONINFO='tarball'
+BUILDTYPE='UEFI64'
+BUILDIMG="$BUILDTYPE-$VERSIONINFO.img"
+
+# Check if running as root
+if [ $(id -u) -ne 0 ]; then
+    echo 'Must be run as root!'
+    exit 1
+fi
+
+# Check prereqs
+[ -f scratch/$SYSLINUX/efi64/efi/syslinux.efi ] || { echo 'Prereqs not available'; exit 1; }
+[ -f scratch/$SYSLINUX/efi64/com32/elflink/ldlinux/ldlinux.e64 ] || { echo 'Prereqs not available'; exit 1; }
+[ -f scratch/buildroot/64bit/images/bzImage ] || { echo 'Prereqs not available'; exit 1; }
+[ -f scratch/buildroot/64bit/images/rootfs.cpio.xz ] || { echo 'Prereqs not available'; exit 1; }
+[ -f scratch/buildroot/64bit/target/sbin/linuxpba ] || { echo 'Prereqs not available'; exit 1; }
+[ -f scratch/buildroot/64bit/target/sbin/sedutil-cli ] || { echo 'Prereqs not available'; exit 1; }
+[ -f buildroot/syslinux.cfg ] || { echo 'Prereqs not available'; exit 1; }
+echo "Building $BUILDTYPE image"
   
-# Start fresh
-sudo rm -rf ${BUILDTYPE} ; mkdir ${BUILDTYPE} ; cd ${BUILDTYPE}
-# make an image file
-dd if=/dev/zero of=${BUILDIMG} bs=1M count=32
-(echo "n";echo "";echo "";echo "";echo "ef00";echo w;echo Y) | gdisk ${BUILDIMG}
-LOOPDEV=`sudo losetup --show -f -o 1048576 ${BUILDIMG}`
-sudo mkfs.vfat $LOOPDEV -n ${BUILDTYPE}
-sudo mkdir image
-sudo mount $LOOPDEV image
-sudo chmod 777 image
-sudo mkdir -p image/EFI/boot
-sudo cp ../scratch/${SYSLINUX}/efi64/efi/syslinux.efi image/EFI/boot/bootx64.efi
-sudo cp ../scratch/${SYSLINUX}/efi64/com32/elflink/ldlinux/ldlinux.e64 image/EFI/boot/
-sudo cp ../scratch/buildroot/64bit/images/bzImage image/EFI/boot/
-sudo cp ../scratch/buildroot/64bit/images/rootfs.cpio.xz image/EFI/boot/
-sudo cp ../buildroot/syslinux.cfg image/EFI/boot/
-sudo umount image
-sudo losetup -d $LOOPDEV
-gzip ${BUILDIMG}
+# Clean slate
+rm -rf $BUILDTYPE
+mkdir $BUILDTYPE
+cd $BUILDTYPE
+
+# Create image file and loopback device
+dd if=/dev/zero of=$BUILDIMG bs=1M count=32
+sfdisk $BUILDIMG < ../layout.sfdisk
+LOOPDEV=$(losetup --show -f -o 1048576 $BUILDIMG)
+mkfs.vfat $LOOPDEV -n $BUILDTYPE
+
+# Mount the image
+mkdir image
+mount $LOOPDEV image
+chmod 644 image
+
+# Copy the system onto the image
+mkdir -p image/EFI/boot
+cp ../scratch/$SYSLINUX/efi64/efi/syslinux.efi image/EFI/boot/bootx64.efi
+cp ../scratch/$SYSLINUX/efi64/com32/elflink/ldlinux/ldlinux.e64 image/EFI/boot/
+cp ../scratch/buildroot/64bit/images/bzImage image/EFI/boot/
+cp ../scratch/buildroot/64bit/images/rootfs.cpio.xz image/EFI/boot/
+cp ../buildroot/syslinux.cfg image/EFI/boot/
+
+# Clean up
+umount image
+losetup -d $LOOPDEV
+gzip $BUILDIMG
diff --git a/images/buildpbaroot b/images/buildpbaroot
--- a/images/buildpbaroot
+++ b/images/buildpbaroot
@@ -1,33 +1,35 @@
-#!/bin/bash
+#! /bin/bash
 set -x
-function die {
-echo An error has occured! Please fix this and start over!
-exit 99
-}
 . conf
+
+function die {
+    echo 'An error has occured! Please fix this and start over!'
+    exit 1
+}
+
 cd scratch
-# clean up and start over
+
+# Clean slate
+rm buildroot-*
 rm -rf buildroot
-git clone ${BUILDROOT} || die
+curl $BUILDROOT/buildroot-$BUILDROOT_TAG.tar.gz -O || die
+tar xf buildroot-$BUILDROOT_TAG.tar.gz
+mv buildroot-$BUILDROOT_TAG buildroot
+
 cd buildroot
-git checkout -b PBABUILD ${BUILDROOT_TAG}  || die
-git reset --hard
-git clean -df
-# add out of tree build directoried and files
-# 64 bit system
+
+# Add out of tree build directories and files
 mkdir 64bit
 cp ../../buildroot/64bit/.config 64bit/
 cp ../../buildroot/64bit/* 64bit/
 cp -r ../../buildroot/64bit/overlay 64bit/
-# 32 bit system
-mkdir 32bit
-cp ../../buildroot/32bit/.config 32bit/
-cp ../../buildroot/32bit/* 32bit/
-cp -r ../../buildroot/32bit/overlay 32bit/
-# add the current buildroot packages
+
+# Add the buildroot packages
 sed -i '/sedutil/d' package/Config.in
 sed -i '/menu "System tools"/a \\tsource "package/sedutil/Config.in"' package/Config.in
+rm -rf package/sedutil
 cp -r ../../buildroot/packages/sedutil/ package/
+
 # Make a distribution from the current source
 cd ../../..
 autoreconf -i
@@ -38,19 +40,16 @@ cp sedutil-*.tar.gz images/scratch/buildroot/dl/
 make distclean
 
 # Expand the distribution tarball so we can use it as the Buildroot override.
-# Override location is specified in the 'local.mk' file in buildroot/{32,64}bit
-# directories.
+# Override location is specified in the 'local.mk' file in buildroot/64bit
+# directory.
 # See also section 8.12.6 "Using Buildroot during development" in the
 # Buildroot user manual.
 cd images/scratch/buildroot/dl
-tar xvfz sedutil-*.tar.gz
+tar xf sedutil-*.tar.gz
 cd ..
 
-# build the rootfs for 64 and 32 bit systems
-echo Making the 64bit PBA Linux system
+# Build the rootfs for 64 bit systems
+echo 'Making the 64bit PBA Linux system'
 make O=64bit 2>&1 | tee 64bit/build_output.txt
-echo Making the 32bit PBA Linux system
-make O=32bit 2>&1 | tee 32bit/build_output.txt
-# back to where we started
+
 cd ../..
-exit 0
diff --git a/images/buildrescue b/images/buildrescue
--- a/images/buildrescue
+++ b/images/buildrescue
@@ -1,87 +1,72 @@
-#!/bin/bash
+#! /bin/bash
 set -x
-## define releases for tools
 . conf
-VERSIONINFO=`git describe --dirty`  || VERSIONINFO=tarball
-BUILDTYPE=RESCUE32
-ROOTDIR=32bit
 
-if [ x${1} == "xRescue32" ] ; then
-	BUILDTYPE="RESCUE32"
-	ROOTDIR="32bit"
-elif [ x${1} == "xRescue64" ] ; then
-	BUILDTYPE="RESCUE64"
-	ROOTDIR="64bit"
-else 
-	echo "NO BUILDTYPE specified defalted to Rescue32"
+VERSIONINFO="$(git describe --dirty)" || VERSIONINFO='tarball'
+BUILDTYPE='RESCUE64'
+ROOTDIR='64bit'
+BUILDIMG="$BUILDTYPE-$VERSIONINFO.img"
+
+# Check if running as root
+if [ $(id -u) -ne 0 ]; then
+    echo 'Must be run as root!'
+    exit 1
 fi
-BUILDIMG=${BUILDTYPE}-${VERSIONINFO}.img
-echo "Building " $BUILDTYPE "image"
-[ -f scratch/${SYSLINUX}/bios/mbr/mbr.bin ] || { echo " prereqs are not available "; exit 1; }
-[ -x scratch/${SYSLINUX}/bios/extlinux/extlinux ] || { echo " prereqs are not available "; exit 1; }
-[ -f scratch/${SYSLINUX}/efi64/efi/syslinux.efi ] || { echo " prereqs are not available "; exit 1; }
-[ -f scratch/${SYSLINUX}/efi64/com32/elflink/ldlinux/ldlinux.e64 ] || { echo " prereqs are not available "; exit 1; }
-[ -f scratch/buildroot/${ROOTDIR}/images/bzImage ] || { echo " prereqs are not available "; exit 1; }
-[ -f scratch/buildroot/${ROOTDIR}/images/rootfs.cpio.xz  ] || { echo " prereqs are not available "; exit 1; }
-[ -x scratch/buildroot/${ROOTDIR}/target/sbin/linuxpba  ] || { echo " prereqs are not available "; exit 1; }
-[ -x scratch/buildroot/${ROOTDIR}/target/sbin/sedutil-cli  ] || { echo " prereqs are not available "; exit 1; }
-[ -f buildroot/syslinux.cfg ] || { echo " prereqs are not available "; exit 1; }
-[ -f UEFI64/UEFI64-*.img.gz ] || { echo " prereqs are not available "; exit 1; }
-[ -f BIOS32/BIOS32-*.img.gz ] || { echo " prereqs are not available "; exit 1; }
-#
-# Remaster the root file system
-sudo rm -rf scratch/rescuefs
-sudo rm -f scratch/buildroot/${ROOTDIR}/images/rescuefs.cpio.xz 
+
+[ -f scratch/$SYSLINUX/efi64/efi/syslinux.efi ] || { echo 'Prereqs not available'; exit 1; }
+[ -f scratch/$SYSLINUX/efi64/com32/elflink/ldlinux/ldlinux.e64 ] || { echo 'Prereqs not available'; exit 1; }
+[ -f scratch/buildroot/$ROOTDIR/images/bzImage ] || { echo 'Prereqs not available'; exit 1; }
+[ -f scratch/buildroot/$ROOTDIR/images/rootfs.cpio.xz ] || { echo 'Prereqs not available'; exit 1; }
+[ -x scratch/buildroot/$ROOTDIR/target/sbin/linuxpba ] || { echo 'Prereqs not available'; exit 1; }
+[ -x scratch/buildroot/$ROOTDIR/target/sbin/sedutil-cli ] || { echo 'Prereqs not available'; exit 1; }
+[ -f buildroot/syslinux.cfg ] || { echo 'Prereqs not available'; exit 1; }
+[ -f UEFI64/UEFI64-*.img.gz ] || { echo 'Prereqs not available'; exit 1; }
+echo "Building $BUILDTYPE image"
+
+# Clean slate
+rm -rf scratch/rescuefs
+rm -f scratch/buildroot/$ROOTDIR/images/rescuefs.cpio.xz 
 mkdir scratch/rescuefs
 cd scratch/rescuefs
-xz --decompress --stdout ../buildroot/${ROOTDIR}/images/rootfs.cpio.xz | sudo cpio -i -H newc -d
-#weird permission denied on etc/issue 
-echo "* ***********************************" > /tmp/issue
-echo "* DTA sedutil rescue image ${BUILDIMG}" >> /tmp/issue
-echo "*" >> /tmp/issue
-echo "* Login as root, there is no password" >> /tmp/issue
-echo "*" >> /tmp/issue
-echo "* ***********************************" >> /tmp/issue
-sudo mv /tmp/issue etc/issue
-sudo rm etc/init.d/S99*
-sudo mkdir -p usr/sedutil
-sudo cp ../../UEFI64/UEFI64-*.img.gz usr/sedutil/
-sudo cp ../../BIOS32/BIOS32-*.img.gz usr/sedutil/
-sudo find . | sudo cpio -o -H newc | xz -9 -C crc32 -c > ../buildroot/${ROOTDIR}/images/rescuefs.cpio.xz
+xz -c ../buildroot/$ROOTDIR/images/rootfs.cpio.xz | cpio -i -H newc -d
+
+# Weird permission denied on etc/issue 
+echo '*************************************' > /tmp/issue
+echo "* DTA sedutil rescue image $BUILDIMG" >> /tmp/issue
+echo '*' >> /tmp/issue
+echo '* Login as root, there is no password' >> /tmp/issue
+echo '*' >> /tmp/issue
+echo '*************************************' >> /tmp/issue
+mv /tmp/issue etc/issue
+rm etc/init.d/S99*
+mkdir -p usr/sedutil
+cp ../../UEFI64/UEFI64-*.img.gz usr/sedutil/
+find . | cpio -o -H newc | xz -9 -C crc32 -c > ../buildroot/$ROOTDIR/images/rescuefs.cpio.xz
 cd ../..
-sudo rm -rf scratch/rescuefs
-#
-sudo rm -rf ${BUILDTYPE} ; mkdir ${BUILDTYPE} ; cd ${BUILDTYPE}
-dd if=/dev/zero of=${BUILDIMG} bs=1M count=75
-if [ ${BUILDTYPE} == "RESCUE32" ] ; then
-	(echo o;echo n;echo p;echo 1;echo "";echo "";echo a;echo 1;echo w) | fdisk -C 100 ${BUILDIMG}
-	dd if=../scratch/${SYSLINUX}/bios/mbr/mbr.bin of=${BUILDIMG} count=1 conv=notrunc bs=512
-else
-	(echo "n";echo "";echo "";echo "";echo "ef00";echo w;echo Y) | gdisk ${BUILDIMG}
-fi
-LOOPDEV=`sudo losetup --show -f -o 1048576 ${BUILDIMG}`
-if [ ${BUILDTYPE} == "RESCUE32" ] ; then
-	sudo mkfs.ext4 $LOOPDEV -L ${BUILDTYPE}
-else
-	sudo mkfs.vfat $LOOPDEV -n ${BUILDTYPE}
-fi
+
+# Create image file and loopback device
+rm -rf $BUILDTYPE
+mkdir $BUILDTYPE
+cd $BUILDTYPE
+dd if=/dev/zero of=$BUILDIMG bs=1M count=75
+sfdisk $BUILDIMG < ../layout.sfdisk
+LOOPDEV=$(losetup --show -f -o 1048576 $BUILDIMG)
+mkfs.vfat $LOOPDEV -n $BUILDTYPE
+
+# Mount the image
 mkdir image
 sudo mount $LOOPDEV image
-sudo chmod 777 image
-if [ ${BUILDTYPE} == "RESCUE32" ] ; then
-	sudo mkdir -p image/boot/extlinux
-	sudo ../scratch/${SYSLINUX}/bios/extlinux/extlinux --install image/boot/extlinux
-	sudo cp ../scratch/buildroot/32bit/images/bzImage  image/boot/extlinux/
-	sudo cp ../scratch/buildroot/32bit/images/rescuefs.cpio.xz image/boot/extlinux/rootfs.cpio.xz
-	sudo cp ../buildroot/syslinux.cfg image/boot/extlinux/extlinux.conf
-else
-	sudo mkdir -p image/EFI/boot
-	sudo cp ../scratch/${SYSLINUX}/efi64/efi/syslinux.efi image/EFI/boot/bootx64.efi
-	sudo cp ../scratch/${SYSLINUX}/efi64/com32/elflink/ldlinux/ldlinux.e64 image/EFI/boot/
-	sudo cp ../scratch/buildroot/64bit/images/bzImage image/EFI/boot/
-	sudo cp ../scratch/buildroot/64bit/images/rescuefs.cpio.xz image/EFI/boot/rootfs.cpio.xz
-	sudo cp ../buildroot/syslinux.cfg image/EFI/boot/
-fi	
-sudo umount image
-sudo losetup -d $LOOPDEV
-gzip ${BUILDIMG}
+sudo chmod 644 image
+
+# Copy the system onto the image
+mkdir -p image/EFI/boot
+cp ../scratch/$SYSLINUX/efi64/efi/syslinux.efi image/EFI/boot/bootx64.efi
+cp ../scratch/$SYSLINUX/efi64/com32/elflink/ldlinux/ldlinux.e64 image/EFI/boot/
+cp ../scratch/buildroot/64bit/images/bzImage image/EFI/boot/
+cp ../scratch/buildroot/64bit/images/rescuefs.cpio.xz image/EFI/boot/rootfs.cpio.xz
+cp ../buildroot/syslinux.cfg image/EFI/boot/
+
+# Clean up
+umount image
+losetup -d $LOOPDEV
+gzip $BUILDIMG
